### ISSUE TITLE
nrobeamaverage is missing

### ISSUE THREAD

**Issue by tnakazato** [casangi/casadocs#9]
It seems that documentation for nrobeamaverage was somehow overlooked during conversion from Plone to readthedoc. Below is the documentation page in Plone. It should be migrated.

https://casa.nrao.edu/casadocs-devel/stable/global-task-list/task_nrobeamaverage/about

**Comment by ryanraba** [comment]
I have no idea why it was skipped, but I manually added it back in. It now appears here:
https://casadocs.readthedocs.io/en/latest/api/tt/casatasks.single.nrobeamaverage.html#casatasks.single.nrobeamaverage

**Comment by tnakazato** [comment]
Thanks @ryanraba! Confirmed that nrobeamaverage is available on GitHub.
